# Generated by Django 3.1.7 on 2021-03-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='invited_user',
        ),
        migrations.AlterField(
            model_name='chat',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='User email'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
